sudo: required
services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - docker build -t get2vj/docker-angular -f Dockerfile.dev .

script:
  - docker run get2vj/docker-angular npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
