sudo: required
services:
  - docker

  # Set DISPLAY for Xvfb
env:
  - DISPLAY=:99.0

# Use APT Addon to install Chrome
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - sh -e /etc/init.d/xvfb start
  - docker build -t get2vj/docker-angular -f Dockerfile.dev .

script:
  - docker run get2vj/docker-angular npm run test
